inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'lib/canuby/argparser.rb'

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'lib/canuby/argparser.rb'

Metrics/PerceivedComplexity:
  Max: 10

Style/AsciiComments:
  AllowedChars: [ä]

Style/Documentation:
  Exclude:
    - 'test/**/*'

Style/GlobalVars:
  AllowedVariables: [$project, $options]

Style/SymbolArray:
  EnforcedStyle: brackets
