AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Naming/ConstantName:
  Enabled: False

Style/AsciiComments:
  AllowedChars: [ä]

Style/GlobalVars:
  AllowedVariables: [$project, $rel_type]

Style/MutableConstant:
  Enabled: False

Style/SymbolArray:
  EnforcedStyle: brackets
