language: ruby
cache: bundler
env:
  - linux=true
rvm:
  - 2.5
  - 2.6
before_install:
  - gem install bundler
jobs:
  include:
    - stage: deploy github releases
      rvm: 2.5
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        prerelease: true
        name: Canuby v$TRAVIS_TAG
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: deploy rubygems
      rvm: 2.5
      deploy:
        provider: rubygems
        gem: canuby
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: github pages
      script: bundle exec rake yard
      rvm: 2.5
      deploy:
        provider: pages
        github-token: $GITHUB_TOKEN
        keep-history: true
        skip-cleanup: true
        local-dir: docs
        on:
          branch: master

notifications:
  webhooks: https://www.travisbuddy.com/
